#!/usr/bin/env bash
# Install vLLM into .venv-vllm and point GraphRAG at it via config/.env.
# Intended for a RunPod GPU pod. Re-running upgrades vLLM and rewrites config/.env.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

CHAT_MODEL="${VLLM_CHAT_MODEL:-google/medgemma-4b-it}"
EMBED_MODEL="${VLLM_EMBED_MODEL:-nomic-ai/nomic-embed-text-v1.5}"
CHAT_PORT="${VLLM_CHAT_PORT:-8000}"
EMBED_PORT="${VLLM_EMBED_PORT:-8001}"
VENV="${ROOT}/.venv-vllm"

install_uv() {
  if command -v uv >/dev/null 2>&1; then
    return 0
  fi
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="${HOME}/.local/bin:${PATH}"
}

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "nvidia-smi was not found. Use a RunPod GPU pod; this script does not install drivers." >&2
  exit 1
fi

nvidia-smi

install_uv
uv venv "${VENV}" --python 3.11
uv pip install --python "${VENV}/bin/python" vllm huggingface_hub

cat > "${ROOT}/config/.env" <<EOF
# Generated by scripts/install_vllm.sh. GraphRAG loads this file next to settings.yaml.
GRAPHRAG_API_KEY=vllm
GRAPHRAG_CHAT_MODEL=${CHAT_MODEL}
GRAPHRAG_API_BASE=http://127.0.0.1:${CHAT_PORT}/v1
GRAPHRAG_EMBED_MODEL=${EMBED_MODEL}
GRAPHRAG_EMBED_API_BASE=http://127.0.0.1:${EMBED_PORT}/v1
EOF

if [[ -n "${HF_TOKEN:-}" ]]; then
  export HUGGING_FACE_HUB_TOKEN="${HF_TOKEN}"
  echo "Downloading ${CHAT_MODEL} and ${EMBED_MODEL}..."
  "${VENV}/bin/huggingface-cli" download "${CHAT_MODEL}"
  "${VENV}/bin/huggingface-cli" download "${EMBED_MODEL}"
else
  echo "HF_TOKEN is unset. google/medgemma-4b-it is gated."
  echo "Accept the license at https://huggingface.co/google/medgemma-4b-it"
  echo "then export HF_TOKEN and re-run this script to prefetch the weights."
fi

echo "vLLM installed in ${VENV}."
echo "Start the servers with: bash scripts/serve_vllm.sh"
